# Generated by Django 4.0.1 on 2022-01-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
