# Generated by Django 4.0.1 on 2022-01-19 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Member', '0001_initial'),
        ('Video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.member')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Video.video')),
            ],
        ),
    ]
