# Generated by Django 4.0.1 on 2022-01-19 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('tag', models.CharField(max_length=10)),
                ('like', models.ManyToManyField(related_name='likes', to='Member.Member')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.member')),
            ],
        ),
    ]
